/*
 * Copyright (C) Balena.io - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

import { getSourceTypes, reverseLink } from './link-traversal';

describe('reverseLink', () => {
	test('should reverse', async () => {
		expect(reverseLink('generated', 'task')).toEqual('was generated by');
	});

	test('should reverse inverse', async () => {
		expect(reverseLink('is owned by', 'loop')).toEqual('owns');
	});

	test('should allow "*", aka "any" types', async () => {
		expect(reverseLink('was built into', 'some-new-type')).toEqual(
			'was built from',
		);
	});

	test('should default to original link', async () => {
		expect(reverseLink('i made this up', 'thread')).toEqual('i made this up');
	});
});

describe('getSourceTypes', () => {
	test('should find source types', async () => {
		expect(getSourceTypes('generated')).toContain('transformer');
	});

	test('should return the any type', async () => {
		expect(getSourceTypes('was built into')).toContain('*');
	});
});
